// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjlxzaizmipqgsfwxoov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqbHh6YWl6bWlwcWdzZnd4b292Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NDMyNzAsImV4cCI6MjA1NTIxOTI3MH0.Xv1r9sS9hs4eDG9tbiXB-_u5yGDYKaR7CD0uQgVblSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);